# Generated by Django 5.2.13 on 2026-08-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CafeInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "venue_name",
                    models.CharField(max_length=200, verbose_name="nazwa lokalu"),
                ),
                (
                    "contact_name",
                    models.CharField(
                        max_length=150,
                        verbose_name="imię osoby kontaktowej",
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="e-mail"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        verbose_name="telefon",
                    ),
                ),
                (
                    "city",
                    models.CharField(max_length=120, verbose_name="miasto"),
                ),
                (
                    "interested_products",
                    models.TextField(verbose_name="interesujące produkty"),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("weekly", "Co tydzień"),
                            ("biweekly", "Co dwa tygodnie"),
                            ("monthly", "Raz w miesiącu"),
                            ("occasionally", "Okazjonalnie"),
                            ("one_off", "Jednorazowo"),
                        ],
                        max_length=20,
                        verbose_name="przewidywana częstotliwość zamówień",
                    ),
                ),
                ("message", models.TextField(verbose_name="wiadomość")),
                (
                    "privacy_consent",
                    models.BooleanField(
                        default=False,
                        verbose_name="zgoda na przetwarzanie danych",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Nowe"),
                            ("contacted", "Skontaktowano się"),
                            ("closed", "Zamknięte"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="utworzono",
                    ),
                ),
            ],
            options={
                "verbose_name": "zapytanie od kawiarni",
                "verbose_name_plural": "zapytania od kawiarni",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CafeLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="nazwa"),
                ),
                (
                    "address",
                    models.CharField(max_length=255, verbose_name="adres"),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        verbose_name="strona lub media społecznościowe",
                    ),
                ),
                (
                    "products_note",
                    models.TextField(
                        help_text=(
                            "Orientacyjnie opisz, jakie produkty są dostępne "
                            "w lokalu."
                        ),
                        verbose_name="informacja o produktach",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0,
                        verbose_name="kolejność",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="widoczne"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="utworzono",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name="zaktualizowano",
                    ),
                ),
            ],
            options={
                "verbose_name": "lokal z produktami Komitywy",
                "verbose_name_plural": "lokale z produktami Komitywy",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="WorkshopInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="imię"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="e-mail"),
                ),
                (
                    "topic",
                    models.CharField(
                        choices=[
                            ("plant_based_buns", "Roślinne drożdżówki"),
                            ("shared_dumpling_making", "Wspólne lepienie"),
                            ("fermentation", "Kiszenie i fermentacja"),
                            ("seasonal_table", "Sezonowy stół"),
                            ("holiday_cooking", "Świąteczne gotowanie"),
                        ],
                        max_length=40,
                        verbose_name="interesujący temat",
                    ),
                ),
                (
                    "preferred_timing",
                    models.CharField(
                        choices=[
                            ("weekday_evening", "Dzień roboczy wieczorem"),
                            ("weekend", "Weekend"),
                        ],
                        max_length=20,
                        verbose_name="preferowany termin",
                    ),
                ),
                (
                    "consent_contact",
                    models.BooleanField(
                        default=False,
                        verbose_name="zgoda na kontakt",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="utworzono",
                    ),
                ),
            ],
            options={
                "verbose_name": "zainteresowanie warsztatami",
                "verbose_name_plural": "zainteresowania warsztatami",
                "ordering": ["-created_at"],
            },
        ),
    ]
