# Generated by Django 5.2.12 on 2026-04-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('confirmation_token', models.CharField(max_length=64, unique=True)),
                ('confirmation_sent_at', models.DateTimeField(blank=True, null=True)),
                ('unsubscribe_token', models.CharField(max_length=64, unique=True)),
                ('is_unsubscribed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Subskrybent',
                'verbose_name_plural': 'Subskrybenci',
            },
        ),
    ]
