# Generated by Django 5.2.12 on 2026-04-02 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('pickup_date', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Oczekujace na platnosc'), ('paid', 'Oplacone'), ('completed', 'Zrealizowane'), ('cancelled', 'Anulowane')], default='pending', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cart_snapshot', models.JSONField(help_text='Kopia koszyka w momencie zamowienia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Zamowienie',
                'verbose_name_plural': 'Zamowienia',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Kategoria produktu',
                'verbose_name_plural': 'Kategorie produktow',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('type', models.CharField(choices=[('ebook', 'Ebook'), ('physical', 'Produkt fizyczny')], default='physical', max_length=10)),
                ('description', models.TextField(help_text='Krotki opis (1-2 zdania) -- wyswietlany na karcie')),
                ('full_description', models.TextField(blank=True, help_text='Pelny opis -- wyswietlany na stronie produktu')),
                ('price', models.DecimalField(decimal_places=2, help_text='Cena w PLN', max_digits=8)),
                ('image', models.ImageField(blank=True, help_text='Zdjecie produktu', null=True, upload_to='products/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.productcategory')),
            ],
            options={
                'verbose_name': 'Produkt',
                'verbose_name_plural': 'Produkty',
                'ordering': ['-created_at'],
            },
        ),
    ]
