# Generated by Django 5.2.12 on 2026-04-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_seed_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='p24_session_id',
            field=models.CharField(blank=True, default='', help_text='Identyfikator sesji Przelewy24', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='ebook_file',
            field=models.FileField(blank=True, help_text='Plik PDF ebooka (tylko dla produktow typu ebook)', null=True, upload_to='ebooks/'),
        ),
    ]
