# Generated by Django 5.2.13 on 2026-06-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_p24_session_id_product_ebook_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Zamówienie', 'verbose_name_plural': 'Zamówienia'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['name'], 'verbose_name': 'Kategoria produktu', 'verbose_name_plural': 'Kategorie produktów'},
        ),
        migrations.AlterField(
            model_name='order',
            name='cart_snapshot',
            field=models.JSONField(help_text='Kopia koszyka w momencie zamówienia'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Oczekujące na płatność'), ('paid', 'Opłacone'), ('completed', 'Zrealizowane'), ('cancelled', 'Anulowane')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(help_text='Krótki opis (1-2 zdania) - wyświetlany na karcie'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ebook_file',
            field=models.FileField(blank=True, help_text='Plik PDF ebooka (tylko dla produktów typu ebook)', null=True, upload_to='ebooks/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='full_description',
            field=models.TextField(blank=True, help_text='Pełny opis - wyświetlany na stronie produktu'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Zdjęcie produktu', null=True, upload_to='products/'),
        ),
    ]
