# Generated by Django 5.2.13 on 2026-08-04 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "shop",
            "0004_alter_order_options_alter_productcategory_options_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderEdition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200,
                        verbose_name="Nazwa edycji",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(blank=True, max_length=200, unique=True),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Opis"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="order-editions/",
                        verbose_name="Zdjęcie",
                    ),
                ),
                (
                    "image_alt",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Tekst alternatywny zdjęcia",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Szkic"),
                            ("upcoming", "Nadchodząca"),
                            ("open", "Otwarta"),
                            ("closed", "Zamknięta"),
                        ],
                        default="draft",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "opens_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Początek zamówień",
                    ),
                ),
                (
                    "closes_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Koniec zamówień",
                    ),
                ),
                (
                    "pickup_details",
                    models.TextField(
                        blank=True,
                        verbose_name="Termin i miejsce odbioru",
                    ),
                ),
                (
                    "payment_details",
                    models.TextField(
                        blank=True,
                        verbose_name="Informacje o płatności",
                    ),
                ),
                (
                    "show_in_archive",
                    models.BooleanField(
                        default=True,
                        verbose_name="Pokaż w archiwum",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Edycja zamówień",
                "verbose_name_plural": "Edycje zamówień",
                "ordering": ["-opens_at", "-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["sort_order", "-created_at"],
                "verbose_name": "Produkt",
                "verbose_name_plural": "Produkty",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="allergens",
            field=models.TextField(
                blank=True,
                default="",
                verbose_name="Alergeny",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="ingredients",
            field=models.TextField(
                blank=True,
                default="",
                verbose_name="Składniki",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="sort_order",
            field=models.PositiveIntegerField(
                default=0,
                verbose_name="Kolejność",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="edition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="shop.orderedition",
                verbose_name="Edycja zamówień",
            ),
        ),
    ]
