# Generated by Django 5.2.13 on 2026-08-13 22:38

from django.db import migrations, models


def prepare_legacy_rzuty_for_review(apps, schema_editor):
    OrderEdition = apps.get_model("shop", "OrderEdition")
    OrderEdition.objects.filter(
        status__in=["upcoming", "open"],
    ).update(status="draft")


def downgrade_new_statuses(apps, schema_editor):
    OrderEdition = apps.get_model("shop", "OrderEdition")
    OrderEdition.objects.filter(status="published").update(status="open")
    OrderEdition.objects.filter(status="paused").update(status="closed")


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0007_rzut_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderedition",
            name="pickup_date",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Dzień odbioru",
            ),
        ),
        migrations.AddField(
            model_name="orderedition",
            name="pickup_ends_at",
            field=models.TimeField(
                blank=True,
                null=True,
                verbose_name="Koniec odbioru",
            ),
        ),
        migrations.AddField(
            model_name="orderedition",
            name="pickup_starts_at",
            field=models.TimeField(
                blank=True,
                null=True,
                verbose_name="Początek odbioru",
            ),
        ),
        migrations.RunPython(
            prepare_legacy_rzuty_for_review,
            reverse_code=downgrade_new_statuses,
        ),
        migrations.AlterField(
            model_name="orderedition",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Szkic"),
                    ("published", "Opublikowany"),
                    ("paused", "Wstrzymany"),
                    ("closed", "Zamknięty"),
                ],
                default="draft",
                max_length=10,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="orderedition",
            name="opens_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Początek sprzedaży",
            ),
        ),
        migrations.AlterField(
            model_name="orderedition",
            name="closes_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Koniec sprzedaży",
            ),
        ),
    ]
