# Generated by Django 5.2.13 on 2026-08-13 22:40

from django.db import migrations, models


def copy_legacy_pickup_details(apps, schema_editor):
    OrderEdition = apps.get_model("shop", "OrderEdition")
    OrderEdition.objects.exclude(pickup_details="").update(
        pickup_instructions=models.F("pickup_details")
    )


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0008_rzut_lifecycle"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderedition",
            name="pickup_address",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Adres odbioru",
            ),
        ),
        migrations.AddField(
            model_name="orderedition",
            name="pickup_instructions",
            field=models.TextField(
                blank=True,
                default="",
                verbose_name="Instrukcja odbioru",
            ),
        ),
        migrations.AddField(
            model_name="orderedition",
            name="pickup_place_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                verbose_name="Nazwa miejsca odbioru",
            ),
        ),
        migrations.AddField(
            model_name="orderedition",
            name="show_upcoming_menu",
            field=models.BooleanField(
                default=True,
                verbose_name="Pokaż menu przed otwarciem sprzedaży",
            ),
        ),
        migrations.RunPython(
            copy_legacy_pickup_details,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
