# Generated by Django 5.2.13 on 2026-08-13 23:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0009_rzut_pickup_and_visibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="rzutitem",
            name="allocated_quantity",
            field=models.PositiveIntegerField(
                default=0,
                editable=False,
                help_text=(
                    "Łączna ilość zablokowana przez aktywne Rezerwacje "
                    "i potwierdzone Zamówienia Rzutu."
                ),
                verbose_name="Przydzielona ilość",
            ),
        ),
        migrations.AddConstraint(
            model_name="rzutitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("allocated_quantity__lte", models.F("pool"))
                ),
                name="rzut_item_allocation_within_pool",
            ),
        ),
    ]
