# Generated by Django 5.2.13 on 2026-08-13 23:49

import django.core.validators
import django.db.models.deletion
import shop.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_rzut_item_allocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedition',
            name='allocation_revision',
            field=models.PositiveBigIntegerField(default=0, editable=False, verbose_name='Wersja przydziału Puli'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Aktywna'), ('confirmed', 'Potwierdzona'), ('expired', 'Wygasła'), ('failed', 'Nieudana')], default='active', max_length=10, verbose_name='Status Rezerwacji')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Imię i nazwisko')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='E-mail Klienta')),
                ('customer_phone', models.CharField(blank=True, default='', max_length=30, verbose_name='Telefon')),
                ('customer_notes', models.CharField(blank=True, default='', max_length=500, verbose_name='Uwagi Klienta')),
                ('pickup_starts_at', models.TimeField(verbose_name='Początek Przedziału Odbioru')),
                ('pickup_ends_at', models.TimeField(verbose_name='Koniec Przedziału Odbioru')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Suma')),
                ('p24_session_id', models.CharField(default=shop.models.generate_rzut_p24_session_id, editable=False, max_length=64, unique=True, verbose_name='Identyfikator sesji P24')),
                ('data_processing_accepted_at', models.DateTimeField(verbose_name='Akceptacja przetwarzania danych')),
                ('terms_accepted_at', models.DateTimeField(verbose_name='Akceptacja regulaminu')),
                ('expires_at', models.DateTimeField(verbose_name='Termin wygaśnięcia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rzut', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='shop.orderedition', verbose_name='Rzut')),
            ],
            options={
                'verbose_name': 'Rezerwacja',
                'verbose_name_plural': 'Rezerwacje',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReservationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Liczba sztuk')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Cena jednostkowa')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.reservation', verbose_name='Rezerwacja')),
                ('rzut_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation_items', to='shop.rzutitem', verbose_name='Pozycja Rzutu')),
            ],
            options={
                'verbose_name': 'Wybrana Pozycja Rzutu',
                'verbose_name_plural': 'Wybrane Pozycje Rzutu',
                'ordering': ['pk'],
            },
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['rzut', 'customer_email', 'status'], name='reservation_customer_status'),
        ),
        migrations.AddConstraint(
            model_name='reservationitem',
            constraint=models.UniqueConstraint(fields=('reservation', 'rzut_item'), name='unique_item_per_reservation'),
        ),
        migrations.AddConstraint(
            model_name='reservationitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='reservation_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='reservationitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='reservation_item_price_nonnegative'),
        ),
    ]
