# Generated by Django 5.2.13 on 2026-08-14 05:56

import django.core.validators
import django.db.models.deletion
import shop.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_rzut_reservations'),
    ]

    operations = [
        migrations.CreateModel(
            name='RzutOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default=shop.models.generate_rzut_order_number, editable=False, max_length=32, unique=True, verbose_name='Numer Zamówienia')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Imię i nazwisko')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='E-mail Klienta')),
                ('customer_phone', models.CharField(blank=True, default='', max_length=30, verbose_name='Telefon')),
                ('customer_notes', models.CharField(blank=True, default='', max_length=500, verbose_name='Uwagi Klienta')),
                ('pickup_starts_at', models.TimeField(verbose_name='Początek Przedziału Odbioru')),
                ('pickup_ends_at', models.TimeField(verbose_name='Koniec Przedziału Odbioru')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Suma')),
                ('payment_status', models.CharField(choices=[('pending', 'Oczekuje'), ('paid', 'Opłacona'), ('not_required', 'Nie wymaga płatności'), ('refunded', 'Zwrócona')], default='pending', max_length=20, verbose_name='Status Płatności')),
                ('payment_method', models.CharField(choices=[('p24', 'Przelewy24'), ('cash', 'Gotówka'), ('manual_transfer', 'Przelew ręczny'), ('other', 'Inna'), ('none', 'Brak płatności')], default='none', max_length=20, verbose_name='Metoda Płatności')),
                ('fulfillment_stage', models.CharField(choices=[('new', 'Nowe'), ('preparing', 'W przygotowaniu'), ('ready', 'Gotowe'), ('picked_up', 'Odebrane'), ('cancelled', 'Anulowane')], default='new', max_length=20, verbose_name='Etap Realizacji')),
                ('p24_session_id', models.CharField(editable=False, max_length=64, unique=True, verbose_name='Identyfikator sesji P24')),
                ('p24_order_id', models.PositiveBigIntegerField(unique=True, verbose_name='Identyfikator zamówienia P24')),
                ('data_processing_accepted_at', models.DateTimeField(verbose_name='Akceptacja przetwarzania danych')),
                ('terms_accepted_at', models.DateTimeField(verbose_name='Akceptacja regulaminu')),
                ('payment_confirmed_at', models.DateTimeField(verbose_name='Potwierdzenie płatności')),
                ('customer_confirmation_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Wysłanie potwierdzenia Klientowi')),
                ('customer_confirmation_error', models.TextField(blank=True, default='', verbose_name='Błąd potwierdzenia Klienta')),
                ('owner_notification_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Wysłanie powiadomienia właścicielowi')),
                ('owner_notification_error', models.TextField(blank=True, default='', verbose_name='Błąd powiadomienia właściciela')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='rzut_order', to='shop.reservation', verbose_name='Rezerwacja')),
                ('rzut', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rzut_orders', to='shop.orderedition', verbose_name='Rzut')),
            ],
            options={
                'verbose_name': 'Zamówienie Rzutu',
                'verbose_name_plural': 'Zamówienia Rzutu',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RzutOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Nazwa Produktu')),
                ('portion', models.CharField(max_length=120, verbose_name='Porcja')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Cena jednostkowa')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Liczba sztuk')),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Suma Pozycji Zamówienia')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.rzutorder', verbose_name='Zamówienie Rzutu')),
                ('rzut_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='shop.rzutitem', verbose_name='Źródłowa Pozycja Rzutu')),
            ],
            options={
                'verbose_name': 'Pozycja Zamówienia',
                'verbose_name_plural': 'Pozycje Zamówienia',
                'ordering': ['pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='rzutorder',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='rzut_order_total_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='rzutorderitem',
            constraint=models.UniqueConstraint(fields=('order', 'rzut_item'), name='unique_rzut_item_per_order'),
        ),
        migrations.AddConstraint(
            model_name='rzutorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='rzut_order_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='rzutorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='rzut_order_item_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='rzutorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('line_total__gte', 0)), name='rzut_order_item_total_nonnegative'),
        ),
    ]
