# Generated by Django 5.2.13 on 2026-08-18 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_rzut_orders'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rzutitem',
            name='rzut_item_allocation_within_pool',
        ),
    ]
