# Generated by Django 5.2.13 on 2026-08-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_remove_rzutitem_rzut_item_allocation_within_pool'),
    ]

    operations = [
        migrations.AddField(
            model_name='rzutorder',
            name='attention_message',
            field=models.TextField(blank=True, default='', verbose_name='Powód pilnej uwagi'),
        ),
        migrations.AddField(
            model_name='rzutorder',
            name='attention_notification_error',
            field=models.TextField(blank=True, default='', verbose_name='Błąd pilnego alertu'),
        ),
        migrations.AddField(
            model_name='rzutorder',
            name='attention_notification_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Wysłanie pilnego alertu'),
        ),
        migrations.AddField(
            model_name='rzutorder',
            name='requires_attention',
            field=models.BooleanField(default=False, verbose_name='Wymaga pilnej uwagi'),
        ),
    ]
