# Generated by Django 5.2.13 on 2026-08-18 13:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_rzutorder_attention_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Kod Rabatowy')),
                ('discount_type', models.CharField(choices=[('percentage', 'Procentowy'), ('fixed_amount', 'Kwotowy')], max_length=20, verbose_name='Rodzaj rabatu')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Wartość rabatu')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='Ważny od')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Ważny do')),
                ('minimum_order_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Minimalna wartość Zamówienia')),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Łączny limit użyć')),
                ('per_customer_limit', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Limit użyć na e-mail')),
                ('allocated_uses', models.PositiveIntegerField(default=0, editable=False, verbose_name='Przydzielone użycia')),
                ('allocation_revision', models.PositiveBigIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rzut', models.ForeignKey(blank=True, help_text='Pozostaw puste, aby Kod działał we wszystkich Rzutach.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discount_codes', to='shop.orderedition', verbose_name='Rzut')),
            ],
            options={
                'verbose_name': 'Kod Rabatowy',
                'verbose_name_plural': 'Kody Rabatowe',
                'ordering': ['code'],
            },
        ),
    ]
