# Generated by Django 5.2.13 on 2026-08-18 13:47

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def preserve_existing_subtotals(apps, schema_editor):
    Reservation = apps.get_model("shop", "Reservation")
    RzutOrder = apps.get_model("shop", "RzutOrder")
    Reservation.objects.update(subtotal=models.F("total"))
    RzutOrder.objects.update(subtotal=models.F("total"))


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_discountcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Rabat'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='shop.discountcode', verbose_name='Kod Rabatowy'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='discount_code_snapshot',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Zapisany Kod Rabatowy'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Suma przed rabatem'),
        ),
        migrations.AddField(
            model_name='rzutorder',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Rabat'),
        ),
        migrations.AddField(
            model_name='rzutorder',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rzut_orders', to='shop.discountcode', verbose_name='Kod Rabatowy'),
        ),
        migrations.AddField(
            model_name='rzutorder',
            name='discount_code_snapshot',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Zapisany Kod Rabatowy'),
        ),
        migrations.AddField(
            model_name='rzutorder',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Suma przed rabatem'),
        ),
        migrations.RunPython(
            preserve_existing_subtotals,
            migrations.RunPython.noop,
        ),
    ]
