# Generated by Django 5.2.13 on 2026-08-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_reservation_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rzutorder',
            name='p24_order_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True, verbose_name='Identyfikator zamówienia P24'),
        ),
    ]
