# Generated by Django 5.2.13 on 2026-08-18 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_rzutorder_p24_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rzutorder',
            name='is_manual',
            field=models.BooleanField(default=False, verbose_name='Zamówienie Ręczne'),
        ),
        migrations.AddField(
            model_name='rzutorder',
            name='manual_creation_token',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True, verbose_name='Token utworzenia Zamówienia Ręcznego'),
        ),
        migrations.AddField(
            model_name='rzutorder',
            name='payment_method_details',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Wyjaśnienie Metody Płatności'),
        ),
        migrations.AlterField(
            model_name='rzutorder',
            name='data_processing_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Akceptacja przetwarzania danych'),
        ),
        migrations.AlterField(
            model_name='rzutorder',
            name='p24_session_id',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True, verbose_name='Identyfikator sesji P24'),
        ),
        migrations.AlterField(
            model_name='rzutorder',
            name='payment_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Potwierdzenie płatności'),
        ),
        migrations.AlterField(
            model_name='rzutorder',
            name='reservation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rzut_order', to='shop.reservation', verbose_name='Rezerwacja'),
        ),
        migrations.AlterField(
            model_name='rzutorder',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Akceptacja regulaminu'),
        ),
        migrations.AddConstraint(
            model_name='rzutorder',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_manual', True), ('p24_session_id__isnull', True), ('reservation__isnull', True)), models.Q(('is_manual', False), ('p24_session_id__isnull', False), ('reservation__isnull', False)), _connector='OR'), name='rzut_order_source_consistent'),
        ),
    ]
