# Generated by Django 5.2.13 on 2026-08-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "shop",
            "0018_rzutorder_is_manual_rzutorder_payment_method_details_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="terms_version",
            field=models.CharField(
                default="",
                max_length=50,
                verbose_name="Wersja zaakceptowanego regulaminu",
            ),
        ),
        migrations.AddField(
            model_name="rzutorder",
            name="terms_version",
            field=models.CharField(
                blank=True,
                default="",
                max_length=50,
                verbose_name="Wersja zaakceptowanego regulaminu",
            ),
        ),
    ]
