# Generated by Django 5.2.13 on 2026-08-19 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_reservation_and_rzutorder_terms_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rzutorder',
            name='internal_note',
            field=models.TextField(blank=True, default='', help_text='Widoczna wyłącznie dla administratorów.', verbose_name='Notatka wewnętrzna'),
        ),
        migrations.AddField(
            model_name='rzutorder',
            name='ready_notification_error',
            field=models.TextField(blank=True, default='', verbose_name='Błąd wiadomości „gotowe”'),
        ),
        migrations.AddField(
            model_name='rzutorder',
            name='ready_notification_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Wysłanie wiadomości „gotowe”'),
        ),
        migrations.CreateModel(
            name='RzutOrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail administratora')),
                ('kind', models.CharField(choices=[('customer_data_changed', 'Zmiana danych Zamówienia Rzutu'), ('fulfillment_stage_changed', 'Zmiana Etapu Realizacji'), ('payment_status_changed', 'Zmiana Statusu Płatności'), ('ready_notification_sent', 'Wysłanie wiadomości „gotowe”'), ('ready_notification_failed', 'Błąd wiadomości „gotowe”'), ('pickup_changed', 'Zmiana odbioru Rzutu')], max_length=40, verbose_name='Rodzaj działania')),
                ('context', models.JSONField(blank=True, default=dict, verbose_name='Kontekst')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Czas')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rzut_order_events', to=settings.AUTH_USER_MODEL, verbose_name='Administrator')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='shop.rzutorder', verbose_name='Zamówienie Rzutu')),
            ],
            options={
                'verbose_name': 'Zdarzenie Zamówienia Rzutu',
                'verbose_name_plural': 'Historia Zamówienia Rzutu',
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
