# Generated by Django 5.2.13 on 2026-08-19 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_rzut_order_fulfillment_audit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='rzutorderevent',
            name='kind',
            field=models.CharField(choices=[('customer_data_changed', 'Zmiana danych Zamówienia Rzutu'), ('fulfillment_stage_changed', 'Zmiana Etapu Realizacji'), ('payment_status_changed', 'Zmiana Statusu Płatności'), ('ready_notification_sent', 'Wysłanie wiadomości „gotowe”'), ('ready_notification_failed', 'Błąd wiadomości „gotowe”'), ('pickup_changed', 'Zmiana odbioru Rzutu'), ('pickup_notification_sent', 'Wysłanie wiadomości o zmianie odbioru'), ('pickup_notification_failed', 'Błąd wiadomości o zmianie odbioru')], max_length=40, verbose_name='Rodzaj działania'),
        ),
        migrations.CreateModel(
            name='RzutPickupChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail administratora')),
                ('before', models.JSONField(verbose_name='Dane odbioru przed zmianą')),
                ('after', models.JSONField(verbose_name='Dane odbioru po zmianie')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Czas')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rzut_pickup_changes', to=settings.AUTH_USER_MODEL, verbose_name='Administrator')),
                ('rzut', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickup_changes', to='shop.orderedition', verbose_name='Rzut')),
            ],
            options={
                'verbose_name': 'Zmiana odbioru Rzutu',
                'verbose_name_plural': 'Zmiany odbioru Rzutu',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='RzutPickupNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Wysłano')),
                ('error', models.TextField(blank=True, default='', verbose_name='Błąd wysyłki')),
                ('change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='shop.rzutpickupchange', verbose_name='Zmiana odbioru Rzutu')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_notifications', to='shop.rzutorder', verbose_name='Zamówienie Rzutu')),
            ],
            options={
                'verbose_name': 'Wiadomość o zmianie odbioru',
                'verbose_name_plural': 'Wiadomości o zmianie odbioru',
                'constraints': [models.UniqueConstraint(fields=('change', 'order'), name='unique_pickup_notification_per_order_change')],
            },
        ),
    ]
