# Generated by Django 5.2.13 on 2026-08-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_pickup_change_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='rzutitem',
            name='withdrawn_quantity',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Sztuki z anulowanych Zamówień Rzutu, które nie wróciły do sprzedaży.', verbose_name='Ilość wycofana z dostępności'),
        ),
    ]
