# Generated by Django 5.2.13 on 2026-08-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_rzutitem_withdrawn_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rzutorder',
            name='cancelled_quantity_restored',
            field=models.BooleanField(blank=True, editable=False, null=True, verbose_name='Sztuki z anulowania przywrócone do Puli'),
        ),
        migrations.AddField(
            model_name='rzutorder',
            name='p24_refund_error',
            field=models.TextField(blank=True, default='', editable=False, verbose_name='Błąd pełnego zwrotu P24'),
        ),
        migrations.AddField(
            model_name='rzutorder',
            name='p24_refund_request_id',
            field=models.CharField(blank=True, default='', editable=False, max_length=45, verbose_name='Identyfikator żądania zwrotu P24'),
        ),
        migrations.AddField(
            model_name='rzutorder',
            name='p24_refund_result',
            field=models.JSONField(blank=True, default=dict, editable=False, verbose_name='Wynik pełnego zwrotu P24'),
        ),
        migrations.AddField(
            model_name='rzutorder',
            name='p24_refunded_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Przyjęcie pełnego zwrotu P24'),
        ),
        migrations.AddField(
            model_name='rzutorder',
            name='p24_refunds_uuid',
            field=models.CharField(blank=True, default='', editable=False, max_length=35, verbose_name='Identyfikator paczki zwrotu P24'),
        ),
        migrations.AlterField(
            model_name='rzutorderevent',
            name='kind',
            field=models.CharField(choices=[('customer_data_changed', 'Zmiana danych Zamówienia Rzutu'), ('fulfillment_stage_changed', 'Zmiana Etapu Realizacji'), ('payment_status_changed', 'Zmiana Statusu Płatności'), ('ready_notification_sent', 'Wysłanie wiadomości „gotowe”'), ('ready_notification_failed', 'Błąd wiadomości „gotowe”'), ('pickup_changed', 'Zmiana odbioru Rzutu'), ('pickup_notification_sent', 'Wysłanie wiadomości o zmianie odbioru'), ('pickup_notification_failed', 'Błąd wiadomości o zmianie odbioru'), ('refund_succeeded', 'Pełny zwrot Przelewy24'), ('refund_requested', 'Zlecenie pełnego zwrotu Przelewy24'), ('refund_failed', 'Błąd pełnego zwrotu Przelewy24')], max_length=40, verbose_name='Rodzaj działania'),
        ),
    ]
