# Generated by Django 5.2.12 on 2026-04-01 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Kategoria',
                'verbose_name_plural': 'Kategorie',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(help_text='Krotki opis (1-2 zdania) -- wyswietlany na karcie')),
                ('ingredients_text', models.TextField(help_text='Skladniki -- kazdy w nowej linii')),
                ('steps_text', models.TextField(help_text='Kroki przygotowania -- kazdy w nowej linii')),
                ('prep_time', models.PositiveSmallIntegerField(help_text='Czas przygotowania w minutach')),
                ('image', models.ImageField(blank=True, help_text='Zdjecie przepisu', null=True, upload_to='recipes/')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='recipes.category')),
            ],
            options={
                'verbose_name': 'Przepis',
                'verbose_name_plural': 'Przepisy',
                'ordering': ['-created_at'],
            },
        ),
    ]
