# Generated by Django 5.2.13 on 2026-06-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_restore_polish_diacritics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(help_text='Krotki opis (1-2 zdania) - wyswietlany na karcie'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients_text',
            field=models.TextField(help_text='Skladniki - kazdy w nowej linii'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='steps_text',
            field=models.TextField(help_text='Kroki przygotowania - kazdy w nowej linii'),
        ),
    ]
