# Generated by Django 5.2.13 on 2026-06-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyResearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_label', models.CharField(db_index=True, help_text='Format ISO YYYY-Www, np. 2026-W23', max_length=16, unique=True)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('raw_research', models.TextField(blank=True, default='')),
                ('formatted_json', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('research_done', 'research_done'), ('formatted', 'formatted'), ('failed', 'failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Weekly research',
                'verbose_name_plural': 'Weekly researches',
                'ordering': ['-date_to'],
            },
        ),
    ]
