# Generated by Django 5.2.13 on 2026-06-02 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('excerpt', models.TextField(blank=True, default='', help_text='Krótki lead 1-2 zdania (max 300 znaków).')),
                ('body', models.TextField(help_text='Markdown. Wspierane rozszerzenia: extra, smarty.')),
                ('tags', models.CharField(blank=True, default='', help_text="Tagi rozdzielone przecinkami, np. 'wegan, brownie, sezon'.", max_length=300)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('published', 'published')], db_index=True, default='draft', max_length=12)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_research', models.ForeignKey(blank=True, help_text="Źródłowy WeeklyResearch, jeśli post powstał z 'Promuj do BlogPost'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='content.weeklyresearch')),
            ],
            options={
                'verbose_name': 'Blog post',
                'verbose_name_plural': 'Blog posts',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['status', '-published_at'], name='content_blo_status_b5b42b_idx')],
            },
        ),
    ]
