# Generated by Django 5.2.13 on 2026-06-08 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorySlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Kolejnosc slajdu (1-based).')),
                ('slide_type', models.CharField(help_text='hook/fact/tip/cta', max_length=20)),
                ('headline', models.CharField(help_text='Twardy bezpiecznik DB; cel redakcyjny <=55 znakow.', max_length=90)),
                ('subtext', models.TextField(blank=True, default='')),
                ('bg_color', models.CharField(default='#f3ead7', help_text='Hex, fallback gdy brak zdjecia.', max_length=9)),
                ('visual_hint', models.TextField(blank=True, default='', help_text='Opis kadru -> zasila AI-prompt.')),
                ('background_image', models.ImageField(blank=True, help_text='Wgrane zdjecie tla (layout A).', null=True, upload_to='weekly_research/story_uploads/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_slides', to='content.weeklyresearch')),
            ],
            options={
                'verbose_name': 'Story slide',
                'verbose_name_plural': 'Story slides',
                'ordering': ['research', 'order'],
                'unique_together': {('research', 'order')},
            },
        ),
    ]
